[package]
name = "egui_winit_vulkano"
version = "0.14.0"
authors = ["hakolao <okkohakola@gmail.com>"]
edition = "2018"
description = "Egui immediate mode gui integration with winit and Vulkano"
homepage = "https://github.com/hakolao/egui_winit_vulkano"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/hakolao/egui_winit_vulkano"
categories = ["gui", "game-development"]
keywords = ["gui", "imgui", "immediate", "portable", "gamedev"]

[dependencies]
copypasta = "0.7.1"
egui = "0.16.0"
image = "0.23.14"
vulkano = { git = "https://github.com/vulkano-rs/vulkano.git", rev = "d36bba1" }
vulkano-shaders = { git = "https://github.com/vulkano-rs/vulkano.git", rev = "d36bba1" }
webbrowser = "0.5.5"
winit = "0.26"

[dev-dependencies]
cgmath = "0.18.0"
egui_demo_lib = "0.16.0"
vulkano-win = { git = "https://github.com/vulkano-rs/vulkano.git", rev = "d36bba1" }
