[package]
name = "egui_winit_vulkano"
version = "0.1.0"
authors = ["hakolao <okkohakola@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
copypasta = "0.7.1"
egui = "0.12.0"
image = "0.23.13"
vulkano = {  version = "0.24.0" }
vulkano-win =  { version = "0.24.0" }
vulkano-shaders = {version = "0.24.0" }
webbrowser = "0.5.5"
winit = "0.25.0"
egui_demo_lib = "0.12.0"

[dev-dependencies]
cgmath = "0.18.0"

