[package]
name = "egui_winit_vulkano"
version = "0.1.0"
authors = ["hakolao <okkohakola@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
copypasta = "0.7.1"
egui = "0.10.0"
image = "0.23.13"
vulkano = { git = "https://github.com/vulkano-rs/vulkano.git", rev = "b390861"}
vulkano-win =  { git = "https://github.com/vulkano-rs/vulkano.git", rev = "b390861"}
vulkano-shaders = { git = "https://github.com/vulkano-rs/vulkano.git", rev = "b390861"}
webbrowser = "0.5.5"
winit = "0.24.0"

[dev-dependencies]
cgmath = "0.18.0"

